name: Deploy Production

on:
  workflow_dispatch:

permissions:
  contents: read

  deploy-Production:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: docker-build

    if: github.event_name == 'pull_request'

    env:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}

    steps:
      - name: Install Render CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/render-oss/cli/main/bin/install.sh | sh
          echo "$HOME/.render/bin" >> "$GITHUB_PATH"
          
      - name: Show image to deploy
        run: |
          echo "Image built:"
          echo "${{ env.IMAGE_NAME }}:${{ github.event.pull_request.head.sha }}"


      - name: Deploy image to Production
        run: |
          render deploys create \
            "${{ secrets.RENDER_PROD_SERVICE_ID }}" \
            --image "${{ env.IMAGE_NAME }}:${{ github.event.pull_request.head.sha }}" \
            --wait \
            --confirm